name: CryptoFuturesBot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - streamlit
  - requests
  - cryptography
  - pip
  - pip:
      - python-dotenv
      - telegram
      
